/// Generated by AssetsRefGenerator on 2020/05/02
class Res {
  static const String background = "assets/background.jpg";
  static const String music_record = "assets/music_record.png";
  static const String splash_eclips = "assets/splash_eclips.gif";
}
